services:
    app.view_handler:
        class: App\Service\View\ViewHandler
        arguments:
            - '@event_dispatcher'
            - '@serializer'

    App\Service\View\ViewHandlerInterface:
        alias: app.view_handler