volumes:
    database_data:

services:
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        build:
            context: docker/php
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    postgres:
        container_name: ${COMPOSE_PROJECT_NAME}-postgres
        image: bitnami/postgresql:16.2.0
        restart: always
        environment:
            POSTGRESQL_USER: ${PROJECT_USER}
            POSTGRESQL_PASSWORD: ${PROJECT_PASSWORD}
            POSTGRESQL_POSTGRES_PASSWORD: ${PROJECT_PASSWORD}
            POSTGRESQL_DATABASE: ${PROJECT_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - database_data:/var/lib/postgresql/data