# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: services/ }

parameters:
    app.host: "%env(APP_HOST)%"

services:
    command_handlers:
        namespace: App\Command\
        resource: '../src/Command/**/*Handler.php'
        autoconfigure: true
        autowire: true

    commands:
        namespace: App\Console\
        resource: '../src/Console/**/*Command.php'
        autoconfigure: true
        autowire: true

    controllers:
        namespace: App\Controller\
        resource: '../src/Controller/**/*Controller.php'
        autoconfigure: true
        autowire: true

    event_listeners:
        namespace: App\EventListener\
        resource: '../src/EventListener/**/*EventListener.php'
        autoconfigure: true
        autowire: true

    form_types:
        namespace: App\Form\
        resource: '../src/Form/**/*Type.php'
        autoconfigure: true
        autowire: true

    repositories:
        namespace: App\Repository\
        resource: '../src/Repository/**/*Repository.php'
        autoconfigure: true
        autowire: true
        tags:
            - app.repository

    security:
        namespace: App\Security\
        resource: '../src/Security/**/*.php'
        autoconfigure: true
        autowire: true
